[versions]
# Android
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
versionCode = "1"
versionName = "1.0"

#Java
javaVersion = "17"

# Kotlin & KSP
kotlinVersion = "1.9.0"
kotlinCompilerExtension = "1.5.2"
ksp = "1.9.0-1.0.13"